== Overview
This software is a virtual environment capable of operating user defined components of any scale and complexity. The framework included in this package provides a set of elements that are used to develop dynamical systems with no structural requirements.  The environment is a platform that supports any system, or collection of systems, defined using this framework with an API that makes it easy to operate and manage results. 

This package is the hybrid systems environment core, which contains only the classes that provide basic functionality, operate the environment, and make up the development framework.  It is separated from other hybrid systems environment packages, which can be found in the additional packages section (coming soon) for robustness purposes.  The core package (this package) is not intended to change other than bug fixes and additional functionality where absolutely necessary to ensure that compatibility is maintained.  All other packages are intended to be expanded over time as new components and tools are developed.  

== Installation
In order to use the Hybrid Systems Environment in a project, it must be included in the build path as a dependency.  The recommended way to do this is by using dependency management tools such as Maven or Gradle to include the package by adding the following code to the build script.

Maven:

[source,xml]
----
<!-- Add repository (if not already included) -->
<repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
</repository>

<!-- Add dependency -->
<dependency>
    <groupId>com.github.be3short</groupId>
    <artifactId>HybridSystemsEnvironment</artifactId>
    <version>-SNAPSHOT</version>
</dependency>
----

Gradle:

[source,java]
----
//Add repository (if not already included):
repositories {
     ...
     maven { url "https://jitpack.io" }
}

//Add dependency:
dependencies {
    ...
    compile 'com.github.be3short:HybridSystemsEnvironment:-SNAPSHOT'
}
----

Alternatively, the binaries can be downloaded and the jar file can be included in the project build path manually.

== Defining Components
Models and components are designed by extending the Hybrid System base class to define behavior.

The following code illustrates how to define a data generator component, which is a dynamical system describing a data generation element such as a sensor or a node in a network.

The state of the data generator is defined in the following code:
[source,java]
----
public class DataGeneratorState extends State
{

	public double dataGenerated; // total amount of data generated
	public double timeToNextData; // time until next data generated

	// Constructor that initializes initial state values
	public DataGeneratorState(double data_generated, double time_to_next)
	{
		dataGenerated = data_generated; // set initial data generated
		timeToNextData = time_to_next; // set initial time until next data
	}
}
----

The parameters of the data generator is defined in the following code:
[source,java]
----
public class DataGeneratorState extends State
{

	public double dataGenerated; // total amount of data generated
	public double timeToNextData; // time until next data generated

	// Constructor that initializes initial state values
	public DataGeneratorState(double data_generated, double time_to_next)
	{
		dataGenerated = data_generated; // set initial data generated
		timeToNextData = time_to_next; // set initial time until next data
	}
}
----

The data generator system is defined in the following code:
[source,java]
----
public class DataGeneratorSystem extends HybridSystem<DataGeneratorState>
{

	public DataGeneratorParameters params; // data generator parameters

	// Constructor that loads data generator state and parameters
	public DataGeneratorSystem(DataGeneratorState state, DataGeneratorParameters parameters)
	{
		super(state); // load data generator state
		params = parameters; // load data generator parameters
	}

	// Checks if data generator state is in flow map
	@Override
	public boolean C(DataGeneratorState x)
	{
		boolean waiting = x.timeToNextData > 0.0;
		return waiting;
	}

	// Computes continuous dynamics of data generator state
	@Override
	public void F(DataGeneratorState x, DataGeneratorState x_dot)
	{
		x_dot.dataGenerated = 0.0;
		x_dot.timeToNextData = -1.0;
	}

	@Override
	// Checks if data generator state is in jump map
	public boolean D(DataGeneratorState x)
	{
		boolean dataGenerated = x.timeToNextData <= 0.0;
		return dataGenerated;
	}

	// Computes discrete dynamics of data generator state
	@Override
	public void G(DataGeneratorState x, DataGeneratorState x_plus)
	{
		x_plus.dataGenerated = x.dataGenerated + params.dataItemSize;
		x_plus.timeToNextData = params.generationInterval;
	}
}
----

== Usage

Using the environment is fairly straightforward; simply create a new HybridEnvironment instance, add hybrid systems, configure the settings, and execute. How to define components and configure the settings are documented in later sections.

The code below illustrates how to configure the environment with a single data generator and run a trial for 20 (simulated) seconds and a maximum of 20 jumps, with the results being saved in the file "resultFile", and a result view being opened.

[source,java]
----
HybridEnvironment environment = new HybridEnvironment(); // instantiate environment

DataGeneratorState dataGenerator = new DataGeneratorState(0.0,1.0); // instantiate state

DataGeneratorParameters generatorParameters = new DataGeneratorParameters(1.0,1.0); // instantiate parameters

DataGeneratorSystem generatorSystem = new DataGeneratorSystem(generatorState,generatorParameters) // instantiate system

environment.addContent(generatorSystem); // add system to environment

environment.start(20.0); // start environment

environment.save(resultFile); // save the results to a file

environment.openResultView(); // open a result view
----

== Adknowledgements
Thank you to the Center for Research in Open Source Software (CROSS) for supporting this project (https://cross.soe.ucsc.edu/CROSS/Home/Home.html).
Additional thanks to Toshiba and Micron for their contributions to this project.  And last but not least thank you to my Advisor, Professor Ricardo Sanfelice (https://hybrid.soe.ucsc.edu), this project would have never happened without him.